# Generated by Django 3.1.7 on 2021-03-28 17:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brewery_type', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=100, null=True)),
                ('address_2', models.CharField(max_length=100, null=True)),
                ('address_3', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('county_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(default='07302', max_length=20)),
                ('website_url', models.URLField()),
                ('phone', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=100)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('latitude', models.FloatField(default=None, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=None, geography=True, null=True, srid=4326)),
                ('tags', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
