# Generated by Django 3.1.7 on 2021-03-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='address_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brewery',
            name='address_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brewery',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='postal_code',
            field=models.CharField(default='07302', max_length=20),
        ),
    ]
