# Generated by Django 3.1.7 on 2021-03-28 13:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0002_auto_20210327_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(
                default=None, geography=True, null=True, srid=4326),
        ),
    ]
