# Generated by Django 3.1.7 on 2021-03-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0004_fill_points'),
        ('breweries', '0003_brewery_point'),
    ]

    operations = [
    ]
